- include_role:
    name: base
  when: kn6plv_aredn_base_loaded is not defined

- name: Create DNS aliases
  dnsalias:
    name: "{{ item.name }}"
    address: "{{ item.address }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ dns_alias | default([]) }}"
  notify: update config"
