- include_role:
    name: base
  when: kn6plv_aredn_base_loaded is not defined

- name: Configure tunnel server
  tunnelserver:
    dnsname: "{{ server.dns_name }}"
    network: "{{ server.network }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    comment: "{{ item.comment | default('') }}"
    enable: "{{ item.enable | default(true) }}"
    index: "{{ idx }}"
  loop: "{{ server.tunnels | default([]) }}"
  loop_control:
    index_var: idx
  notify: update tunnels
  when: server is defined

- name: Configure tunnel clients
  tunnelclient:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    network: "{{ item.network }}"
    comment: "{{ item.comment | default('') }}"
    state: "{{ item.state | default('present') }}"
    enable: "{{ item.enable | default(true) }}"
  loop: "{{ clients | default([]) }}"
  notify: update tunnels
  when: clients is defined
