argument_specs:
  main:
    short_description: Advanced configuration changes
    options:
      advanced:
        description: "List of configuration requirements"
        type: list
        element: dict
        options:
          name:
            description: "Configuration name"
            required: true
            choices:
              - "aredn.@map[0].maptiles"
              - "aredn.@map[0].leafletcss"
              - "aredn.@map[0].leafletjs"
              - "aredn.@downloads[0].firmwarepath"
              - "aredn.@downloads[0].pkgs_core"
              - "aredn.@downloads[0].pkgs_base"
              - "aredn.@downloads[0].pkgs_arednpackages"
              - "aredn.@downloads[0].pkgs_luci"
              - "aredn.@downloads[0].pkgs_packages"
              - "aredn.@downloads[0].pkgs_routing"
              - "aredn.@downloads[0].pkgs_telephony"
              - "aredn.@downloads[0].pkgs_freifunk"
              - "aredn.@tunnel[0].maxclients"
              - "aredn.@tunnel[0].maxservers"
              - "aredn.@meshstatus[0].lowmem"
              - "aredn.@meshstatus[0].lowroutes"
              - "aredn.@alerts[0].localpath"
              - "aredn.@alerts[0].pollrate"
          value:
            description: "Configuration value"
            required: true
