- name: Install package
  opkg:
    name: "{{ item.url | basename }}"
    pkg: "/root/{{ item.url | basename }}"
    state: "{{ item.state | default('present') }}"
    update_cache: true
    cache_valid_time: 604800 # 1 week
    reinstall: "{{ packagescopy.changed or (item.force | default(false)) }}"
  register: install
- name: Wait for node to reinitialize
  wait_for_connection:
    delay: 10
    timeout: 600
  when: install.changed and (item.wait | default(false))
