- name: Download packages to install
  get_url:
    url: "{{ item.url }}"
    dest: /tmp
    force: true
    mode: "644"
  delegate_to: localhost
  run_once: true
  loop: "{{ packages }}"
  when: packages is defined

- name: Copy packages to node
  copy:
    src: "/tmp/{{ item.url | basename }}"
    dest: "/root/{{ item.url | basename }}"
    mode: "644"
  loop: "{{ packages }}"
  register: packagescopy
  when: packages is defined

- name: Install packages
  include_tasks: install.yml
  loop: "{{ packages }}"
  when: packages is defined
