- name: Download firmware
  set_fact:
    firmware: "{{ lookup('kn6plv.aredn.firmware', version) }}"
- name: Update node firmware
  block:
    - name: Upload firmware to node
      copy:
        src: "{{ firmware.file }}"
        dest: /tmp/firmware
        mode: "644"
    - name: Update node
      firmware:
        file: /tmp/firmware
        sha256: "{{ firmware.sha256 }}"
    - name: Wait for reboot
      wait_for_connection:
        delay: 10
        timeout: 600
  when: firmware.version != ansible_distribution_version or force
