- include_role:
    name: base
  when: kn6plv_aredn_base_loaded is not defined

- name: Forward ports
  portforward:
    interface: "{{ item.interface }}"
    type: "{{ item.type | default(both) }}"
    port: "{{ item.port }}"
    address: "{{ item.address | default('localhost') }}"
    lanport: "{{ item.lanport | item.port }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ port_forward }}"
  notify: update config
  when: port_forward is defined
